package org.emp.gl.gui_control;

import org.emp.gl.core.lookup.Lookup;
import org.emp.gl.actions.Action;
/**
 *
 * @author pc
 */
public class Gui_Control extends javax.swing.JFrame {

    /**
     * Creates new form Gui_Control
     */
    public Gui_Control() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mode = new javax.swing.JButton();
        config = new javax.swing.JButton();
        increment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        setLocation(new java.awt.Point(500, 350));
        setPreferredSize(new java.awt.Dimension(400, 300));

        mode.setText("Mode");
        mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeActionPerformed(evt);
            }
        });

        config.setText("Confige");
        config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configActionPerformed(evt);
            }
        });

        increment.setText("Increment");
        increment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(mode)
                .addGap(18, 18, 18)
                .addComponent(config)
                .addGap(18, 18, 18)
                .addComponent(increment)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mode)
                    .addComponent(config)
                    .addComponent(increment))
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeActionPerformed
        // mode
        Action mywatch = Lookup.getInstance().getService(Action.class);
        mywatch.do_mode();
        
    }//GEN-LAST:event_modeActionPerformed

    private void configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configActionPerformed
        // config 
        Action mywatch = Lookup.getInstance().getService(Action.class);
        mywatch.do_config();
    }//GEN-LAST:event_configActionPerformed

    private void incrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementActionPerformed
        // increment par délégation 
        Action mywatch = Lookup.getInstance().getService(Action.class);
        mywatch.do_increment();
    }//GEN-LAST:event_incrementActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton config;
    private javax.swing.JButton increment;
    private javax.swing.JButton mode;
    // End of variables declaration//GEN-END:variables
}
